version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    volumes:
      - server_data:/app/server/files
    ports:
      - "8090:8080"
    networks:
      - dropbox_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 3

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    volumes:
      - client_data:/app/client/sync_dir
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    depends_on:
      server:
        condition: service_healthy
    networks:
      - dropbox_network
    command: ["/bin/bash"]

volumes:
  server_data:
  client_data:

networks:
  dropbox_network:
    driver: bridge
